# Processed E-commerce Dataset (Day 9)
This notebook loads Orders, Customers, and Products CSVs, merges them, demonstrates `concat()`, uses `apply()` to compute total price, performs datetime transformations, and exports a final processed CSV.

In [8]:
import pandas as pd
from pathlib import Path
base = Path('.')

In [9]:
orders = pd.read_csv(base / 'Day9_Orders.csv', parse_dates=['Order_Date'])
customers = pd.read_csv(base / 'Day9_Customers.csv')
products = pd.read_csv(base / 'Day9_Products.csv')
orders.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [10]:
mid = len(orders) // 2
orders_part1 = orders.iloc[:mid].copy()
orders_part2 = orders.iloc[mid:].copy()
orders_rejoined = pd.concat([orders_part1, orders_part2], ignore_index=True)

In [11]:

df = orders_rejoined.merge(
    customers,
    on='Customer_ID',
    how='left'
).merge(
    products,
    on='Product_ID',
    how='left'
)
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df['Total_Price'] = df['Quantity'] * df['Unit_Price']
df['Order_Month'] = df['Order_Date'].dt.month_name()
df['Order_Day'] = df['Order_Date'].dt.day
df['Order_Weekday'] = df['Order_Date'].dt.day_name()
df[['Order_Date','Order_Month','Order_Day','Order_Weekday']].head()

  Order_Date Order_Month  Order_Day Order_Weekday
0 2026-02-19    February         19      Thursday
1 2026-01-25     January         25        Sunday
2 2026-02-26    February         26      Thursday
3 2026-03-04       March          4     Wednesday
4 2026-03-29       March         29        Sunday

In [ ]:
cols = df.columns.tolist()
final_df = df[cols].sort_values(by='Order_Date').reset_index(drop=True)
final_df.to_csv('processed_ecommerce_dataset.csv', index=False)
print('Exported processed_ecommerce_dataset.csv')

Exported processed_ecommerce_dataset.csv